[package]
name = "ledfx-senders"
version = "0.3.1"
edition = "2024"
rust-version = "1.94"
publish = false
autotests = false

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
socket2 = "0.6"
pyo3 = { version = "=0.29.2", features = ["extension-module"] }

[profile.release]
debug = 1

[[bin]]
name = "ledfx-receiver"
path = "bench/receiver/main.rs"
