from collections.abc import Sequence
from typing import TypeAlias

Span: TypeAlias = tuple[int, int, int, int]

def engine_info() -> dict[str, str]: ...

class _TestLockGate:
    def __init__(self) -> None: ...
    def wait_entered(self) -> None: ...
    def release(self) -> None: ...
    @property
    def timed_out(self) -> bool: ...

class PacketBanks:
    def __init__(
        self, templates: Sequence[bytes], spans: Sequence[Span], count: int
    ) -> None: ...
    def update(self, frame: object) -> None: ...
    def snapshot(self, staging: bool = False) -> tuple[bytes, ...]: ...
    def capacities(self) -> list[int]: ...

class Engine:
    def __init__(
        self,
        templates: Sequence[bytes],
        spans: Sequence[Span],
        count: int,
        destinations: Sequence[str],
        sync: bytes,
        discovery: Sequence[bytes],
    ) -> None: ...
    @staticmethod
    def _test_engine(
        templates: Sequence[bytes],
        spans: Sequence[Span],
        count: int,
        destinations: Sequence[str],
        sync: bytes,
        discovery: Sequence[bytes],
        mode: str,
        backend: str = "batched",
        batch_size: int = 64,
        override_destination: str | None = None,
    ) -> Engine: ...
    def _test_hold_lock(self, gate: _TestLockGate) -> None: ...
    def _test_loopback_multicast(self) -> None: ...
    def send(self, frame: object, now: float) -> None: ...
    def service(self, now: float) -> None: ...
    def close(self, blackout: bool, now: float) -> None: ...
    @property
    def closed(self) -> bool: ...
    def counters(self) -> tuple[int, int, int]: ...
    def transport_info(self) -> tuple[str, int, int, int]: ...
    def cleanup_error(self) -> str | None: ...
    def captures(self) -> list[tuple[bytes, str]]: ...
    def committed_copy(self) -> list[bytes]: ...

class PacketEngine:
    def __init__(
        self,
        protocol: str,
        count: int,
        destination: str,
        identifier: int,
        mode: str = "socket",
        backend: str = "batched",
        batch_size: int = 64,
        override_destination: str | None = None,
    ) -> None: ...
    def _test_hold_lock(self, gate: _TestLockGate) -> None: ...
    def send(self, frame: object) -> None: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def counters(self) -> tuple[int, int, int]: ...
    def transport_info(self) -> tuple[str, int, int, int]: ...
    def captures(self) -> list[tuple[bytes, str]]: ...
    def committed_copy(self) -> list[bytes]: ...

class StatefulEngine:
    def __init__(
        self,
        protocol: str,
        pixels: int,
        destination: str,
        mode_name: str,
        paths: list[bytes],
        timeout: int,
        minimise: bool,
        interval: float,
        mode: str = "socket",
        backend: str = "batched",
        batch_size: int = 64,
        override_destination: str | None = None,
    ) -> None: ...
    def send(self, frame: object, kind: int, now: float) -> None: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def _test_hold_lock(self, gate: _TestLockGate) -> None: ...
    def counters(self) -> tuple[int, int, int]: ...
    def frame_counters(self) -> tuple[int, int, int]: ...
    def captures(self) -> list[tuple[bytes, str]]: ...
    def committed_copy(self) -> list[bytes]: ...
    def transport_info(self) -> tuple[str, int, int, int]: ...
